esphome:
  name: sumptank
  platform: ESP32
  board: pico32
  includes:
    - ultrasonic_sensor.h

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:

i2c:
  sda: 26
  scl: 32
  scan: True
  id: bus

light:
  - platform: neopixelbus
    type: GRB
    pin: 27
    num_leds: 1
    id: status_light

sensor:
  - platform: custom
    lambda: |-
      auto u_sensor = new UltrasonicSensor();
      App.register_component(u_sensor);
      return {u_sensor};

    sensors:
      name: "Tank Water Distance"
      unit_of_measurement: mm
      accuracy_decimals: 0
      filters:
        - median:
            window_size: 30
            send_every: 30
            send_first_at: 15
      on_value_range:
        - below: 200
          then:
            - light.turn_on:
                id: status_light
                red: 0.5
                green: 0
                blue: 0
        - above: 20
          below: 500
          then:
            - light.turn_on:
                id: status_light
                red: 0.5
                green: 0.5
                blue: 0
        - above: 500
          then:
            - light.turn_off:
                id: status_light
