# Example configuration entry
esphome:
  name: caldisplay
  includes:
    - urlimage.h

esp32:
  board: esp-wrover-kit

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

substitutions:
  image_url: !secret image_url

captive_portal:

ota:

api:

switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true

  - platform: template
    name: "Inkplate Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);

  - platform: template
    name: "Inkplate Partial Updating"
    lambda: return id(inkplate_display).get_partial_updating();
    turn_on_action:
      - lambda: id(inkplate_display).set_partial_updating(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_partial_updating(false);

sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35
  - platform: template
    name: "Inkplate Battery Voltage"
    lambda: |-
      id(battery_read_mosfet).turn_on();
      delay(1);
      float adc = id(battery_voltage).sample();
      id(battery_read_mosfet).turn_off();
      return adc;
    filters:
      - multiply: 2

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

binary_sensor:
  - platform: status
    name: "Inkplate Status"
    id: system_status

  - platform: gpio
    name: "Inkplate Touch Pad 1"
    pin:
      mcp23xxx: mcp23017_hub
      number: 10
    on_press:
      - component.update: inkplate_display
  - platform: gpio
    name: "Inkplate Touch Pad 2"
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
  - platform: gpio
    name: "Inkplate Touch Pad 3"
    pin:
      mcp23xxx: mcp23017_hub
      number: 12

time:
  - platform: sntp
    id: esptime

http_request:
  useragent: esphome/device
  timeout: 10s

display:
  - platform: inkplate6
    model: inkplate_10
    id: inkplate_display
    greyscale: true
    partial_updating: false
    update_interval: 60s

    ckv_pin: 32
    sph_pin: 33
    gmod_pin:
      mcp23xxx: mcp23017_hub
      number: 1
    gpio0_enable_pin:
      mcp23xxx: mcp23017_hub
      number: 8
    oe_pin:
      mcp23xxx: mcp23017_hub
      number: 0
    spv_pin:
      mcp23xxx: mcp23017_hub
      number: 2
    powerup_pin:
      mcp23xxx: mcp23017_hub
      number: 4
    wakeup_pin:
      mcp23xxx: mcp23017_hub
      number: 3
    vcom_pin:
      mcp23xxx: mcp23017_hub
      number: 5

    lambda: |-
      it.fill(COLOR_ON);
      show_url_bitmap(&it, "${image_url}", 50, 50, 1100, 725);
